### ISSUE TITLE
Invalid character '\u0031

### ISSUE THREAD

**Issue by nuke99** [nVisium/xssValidator#17]
I'm getting these errors Im not sure why 

```
Parse error: SyntaxError: Invalid character '\u0031'
Parse error: TypeError: undefined is not a constructor (evaluating 'gbar.qfgq()')
```

**Comment by thec00n** [comment]
I have this issue as well. I am running phantomjs 2.1.1. Would appreciate help on how to resolve this. 

Parse error: SyntaxError: Invalid character '\u0031'

**Comment by grampae** [comment]
I know that I am responding to an old old post, however I had this same issue and the fix was that there were invisible blank spaces in the xss.js which were translated as '\u0031'.  I just opened up xss.js in nano and they were actually highlighted.  So I just backspaced until they went away and all works after that.   Thought I would put this here for future people having this problem.

**Comment by nvisium-shawn-smith** [comment]
Thanks for the fix @grampae!
